---
# tasks file for copying arangodb systemd unit and starting it

- name: Set the arangodb download url based on version
  set_fact:
    arangodb_download_url={{ arangodb_repository[arangodb_version] }}

- name: Extract the folder name from download url
  shell: echo {{ arangodb_download_url | basename }} | sed 's/\.tar\.gz//g'
  register: arangodb_folder_name

- name: Create the starter_join_ips variable
  set_fact: 
    starter_join_ips: |
      {% for node in arangodb_agents %}{{ node }}:{{ arangodb_starter_port }}{% if not loop.last %},{% endif %}{% endfor %}

- name: Copy systemd file in to /etc/systemd/system
  ansible.builtin.template:
    src: "templates/{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: '644'
  become: true
  loop: "{{ server_type }}"
  
- name: Start the service
  ansible.builtin.systemd:
    name: "{{ item }}.service"
    state: started
    daemon_reload: yes
  become: true
  loop: "{{ server_type }}"

