---                                                                                                                            
- name: Gather facts from the localhost 
  hosts: localhost
  

- hosts: agents                                                                                                                
  roles:                                                                                                                       
    - arangodb_log_collect
  vars:
    folder_name_timestamp: "{{ hostvars['localhost'].ansible_date_time.iso8601_basic_short }}"
    log_foldername: "/tmp/arangodb_log_collect"
    