---                                                                                                                            
- hosts: agents                                                                                                                
  roles:                                                                                                                       
    - ../roles/arangodb_starter_uninstall
